import { Geist, Geist_Mono } from "next/font/google";
import "./global.scss";
import {Navigation} from "./components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <Navigation />
        </header>
        {children}
        <footer>
          <h1>This is the footer</h1>
          <p>© 2023 Your Company Name. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
